### ISSUE TITLE
Null bytes in the first two lines of inputDB confuse 'read' functions.

### ISSUE THREAD

**Issue by eshom** [timriffe/covid_age#66] opened 2020-12-29 16:21 UTC
The first two lines of in 'inputDB.csv' have some bytes which cause me problems when trying to read the file.
In *R*, the following error message is printed while trying to run `readr::read_csv("inputDB.csv", skip = 1)`:
```
Error in make.names(x) : invalid multibyte string at '<a2><9b>y<bd>X'
```

I've attached the first 10 lines of the problematic 'inputDB':
[inputDB-head.zip](https://github.com/timriffe/covid_age/files/5751267/inputDB-head.zip)

On Linux, it looks like these bytes cause the file to be recognized as a `gzip` type, while it should be plain text.
```bash
$ file inputDB-head.csv
inputDB-head.csv: gzip compressed data, from HPFS filesystem (OS/2, NT), original size modulo 2^32 172376364
```

**Comment by timriffe** [comment] 2020-12-29 17:44
Thanks for reporting, I've reproduced the error and am looking into it, will repost as soon as file is fixed.

**Comment by timriffe** [comment] 2020-12-29 17:51
well, the file is corrupted in 13k places, sooooo, looks like I'll recompile the whole inputDB, which takes some hours, please hang in there and refer to earlier versions on OSF if needed.

**Comment by eshom** [comment] 2020-12-29 19:28
Alright, thank you for the quick response!

**Comment by timriffe** [comment] 2020-12-31 08:06
fixed now: switching `write_lines()` and `write_csv()` to `data.table::fwright()` took care of it. Otherwise mysterious. Thanks again for reporting!

**Closed by timriffe** 2020-12-31 08:06 UTC
